### ISSUE TITLE
Does this cache into RAM vs on the SD/HDD for example?

### ISSUE THREAD

**Issue by marksev1** [CANDY-LINE/node-red-contrib-cache#1]
As title says.

**Comment by dbaba** [comment]
This module just uses RAM rather than SD/HDD (disk).
If you need persistency, you can use file, mondodb, sqlite or other database node.
The goal of the node is to provide an easy way to store data to RAM without the function node coding (without using `global.*`/`flow.*`). For advanced users, they can use the function node instead.

**Comment by marksev1** [comment]
So this doesn't then write to SD or HDD?

It writes into RAM right...Can I put a database into RAM, If SBC won't reboot the database should be stored in RAM right? And I can copy it on SD once a week or something.

Is it possible with this node?

**Comment by dbaba** [comment]
No, it doesn't write to SD/HDD.
I think I understood what you'd like to do. However, in order to achieve your goal, this node doesn't help unfortunately because it doesn't have a way to draw all data from the cache store.
